# Generated by Django 4.1.3 on 2022-11-13 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Cliente')),
                ('rutCliente', models.IntegerField(max_length=12, verbose_name='Rut Cliente')),
                ('dvRut', models.IntegerField(max_length=1, verbose_name='DV Rut')),
                ('nombreCliente', models.CharField(max_length=50, verbose_name='Nombre Cliente')),
                ('apellidoCliente', models.CharField(max_length=50, verbose_name='Apellido Cliente')),
                ('correoCliente', models.EmailField(max_length=50, verbose_name='Correo Cliente')),
                ('direccionCliente', models.CharField(max_length=50, verbose_name='Direccion Cliente')),
                ('telefonoCliente', models.CharField(max_length=9, verbose_name='Telefono Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaPyme',
            fields=[
                ('idPyme', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Pyme')),
                ('nombrePyme', models.CharField(max_length=50, verbose_name='Nombre Pyme')),
                ('rutPyme', models.CharField(max_length=12, verbose_name='Rut Pyme')),
                ('bancoPyme', models.CharField(choices=[('CHI', 'Banco de Chile'), ('SAN', 'Banco Santander-Santiago'), ('SCO', 'Banco Scotiabank'), ('EST', 'Banco del Estado de Chile'), ('FAL', 'Banco Falabella'), ('DES', 'Banco del Desarrollo'), ('BIC', 'Banco Bice'), ('CON', 'Banco Consorcio'), ('BCI', 'Banco de Credito e Inversiones'), ('ITA', 'Banco Itau'), ('SEC', 'Banco Security'), ('CIT', 'Citibank N.A'), ('INT', 'Banco Internacional')], max_length=4, verbose_name='Banco Pyme')),
                ('tipoCuentaPyme', models.CharField(choices=[('COR', 'Cuenta Corriente/Cuenta Vista'), ('AHOR', 'Cuenta Ahorro')], max_length=4, verbose_name='Tipo cuenta Banco Pyme')),
                ('cuentaBancoPyme', models.CharField(max_length=15, verbose_name='Cuenta Bancaria Pyme')),
                ('correoPyme', models.EmailField(max_length=100, verbose_name='Email Pyme')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Producto')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('descripcionProducto', models.TextField(max_length=500, verbose_name='Descripcion Producto')),
                ('activoProducto', models.BooleanField(default=True, verbose_name='active')),
                ('precioProducto', models.PositiveIntegerField(verbose_name='Precio Producto')),
                ('imagenProducto', models.ImageField(upload_to='imgprodcuto')),
                ('stockProducto', models.PositiveIntegerField(verbose_name='Stock Producto')),
                ('categoriaProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('pymeProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresapyme')),
            ],
        ),
        migrations.CreateModel(
            name='registro',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Usuario')),
                ('nombreUsuario', models.CharField(max_length=50, verbose_name='Nombre Usuario')),
                ('correoUsuario', models.EmailField(max_length=50, verbose_name='Correo Usuario')),
                ('contraseñaUsuario', models.CharField(max_length=50, verbose_name='Contraseña Usuario')),
                ('telefonoUsuario', models.CharField(max_length=9, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('idVenta', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Venta')),
                ('cantidadProducto', models.PositiveIntegerField(verbose_name='Cantidad de producto')),
                ('totalVenta', models.PositiveIntegerField(verbose_name='Total venta')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('idPyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresapyme')),
            ],
        ),
        migrations.CreateModel(
            name='pagoPyme',
            fields=[
                ('idPago', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Pago')),
                ('montoTotal', models.IntegerField(verbose_name='monto Pago')),
                ('fechaPago', models.DateField(verbose_name='fecha Pago')),
                ('idPyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresapyme')),
            ],
        ),
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('idDelivery', models.AutoField(primary_key=True, serialize=False, verbose_name='ID delivery')),
                ('comentarioDelivery', models.CharField(max_length=50, verbose_name='Comentario delivery')),
                ('idventa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta')),
            ],
        ),
        migrations.CreateModel(
            name='comentarioProducto',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Comentario')),
                ('comentarioProducto', models.CharField(max_length=500, verbose_name='Comentario Produto')),
                ('valoracion', models.PositiveIntegerField(verbose_name='Valoracion')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('idVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta')),
            ],
        ),
        migrations.CreateModel(
            name='boleta',
            fields=[
                ('idBoleta', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Boleta')),
                ('fechaBoleta', models.DateTimeField(verbose_name='Fecha de Boleta')),
                ('idVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta')),
            ],
        ),
    ]
